from __future__ import annotations

import re

MAX_TARGETS = 128
MAX_SCRIPTS = 5_000
MAX_BREAKPOINTS = 1_000
MAX_BREAKPOINT_LOCATIONS = 256
MAX_WATCHES = 100
MAX_WATCH_EXPRESSION_BYTES = 4_096
MAX_CONSOLE_ENTRIES = 500
MAX_CONSOLE_ARGUMENTS = 32
MAX_CALL_FRAMES = 64
MAX_ASYNC_STACK_DEPTH = 32
MAX_SCOPES_PER_FRAME = 12
MAX_SCOPE_PROPERTIES = 100
MAX_TOTAL_SCOPE_PROPERTIES = 2_000
MAX_SCRIPT_SOURCE_BYTES = 2 * 1024 * 1024
MAX_BREAKPOINT_TEXT_BYTES = 4_096
MAX_XHR_BREAKPOINTS = 100
MAX_EVENT_BREAKPOINTS = 256
MAX_LIVE_OBJECT_RESULTS = 50
MAX_LIVE_OBJECT_SCAN = 25_000
MAX_LIVE_OBJECT_QUERY_BYTES = 512
MAX_LIVE_OBJECT_SHAPE_BYTES = 4_096
MAX_LIVE_OBJECT_PREVIEW_PROPERTIES = 16
MAX_LIVE_OBJECT_SEARCH_PROPERTIES = 256
LIVE_OBJECT_SEARCH_TIMEOUT_MS = 750
MAX_HEAP_SNAPSHOT_BYTES = 256 * 1024 * 1024
MAX_HEAP_SNAPSHOT_CHUNK_BYTES = 8 * 1024 * 1024
MAX_HEAP_SNAPSHOT_RESULTS = 50
MAX_HEAP_RETAINING_PATH = 12
MAX_HEAP_INCOMING_REFERENCES = 12
HEAP_SNAPSHOT_CAPTURE_TIMEOUT_SECONDS = 60.0
HEAP_SNAPSHOT_SEARCH_TIMEOUT_SECONDS = 20.0
HEAP_SNAPSHOT_DIFF_TIMEOUT_SECONDS = 60.0
HEAP_SNAPSHOT_PROBE_TIMEOUT_SECONDS = 20.0
MAX_MEMORY_ORIGIN_TRACE_STEPS = 32
MAX_MEMORY_ORIGIN_TRACE_BEFORE_STEPS = 8
MAX_MEMORY_ORIGIN_TRACE_AFTER_STEPS = 16
MEMORY_ORIGIN_TRACE_IDLE_TIMEOUT_SECONDS = 2.5
MEMORY_ORIGIN_TRACE_TIMEOUT_SECONDS = 5 * 60.0
MAX_ACTIVE_PORT_BYTES = 4_096
MAX_TARGET_LIST_BYTES = 2 * 1024 * 1024
MAX_TARGET_ID_BYTES = 4_096
MAX_TARGET_TYPE_BYTES = 128
MAX_TARGET_URL_BYTES = 64 * 1024
MAX_REMOTE_TEXT_BYTES = 4_096
MAX_NATIVE_TRANSPORT_ERROR_BYTES = 4_096
NATIVE_TRANSPORT_STARTUP_TIMEOUT_SECONDS = 3.0
NATIVE_TRANSPORT_WRITE_TIMEOUT_SECONDS = 5.0
NATIVE_TRANSPORT_PROTOCOL_HEADER = b"REB\x01"
MAX_INTERCEPTION_URL_BYTES = 8 * 1024
MAX_INTERCEPTION_PATTERN_BYTES = 2 * 1024
MAX_INTERCEPTION_METHOD_BYTES = 32
MAX_INTERCEPTION_HEADERS = 64
MAX_INTERCEPTION_HEADER_NAME_BYTES = 128
MAX_INTERCEPTION_HEADER_VALUE_BYTES = 2 * 1024
MAX_INTERCEPTION_HEADER_BYTES = 16 * 1024
MAX_INTERCEPTION_BODY_BYTES = 64 * 1024
MAX_INTERCEPTION_RESPONSE_BYTES = 64 * 1024
MAX_INTERCEPTION_AUDIT_ENTRIES = 128
MAX_INTERCEPTION_PENDING_REQUESTS = 16
INTERCEPTION_RUN_TIMEOUT_SECONDS = 15.0
MAX_REPEATER_HISTORY_ENTRIES = 24
MAX_REPEATER_HISTORY_BYTES = 512 * 1024
MAX_REPEATER_VARIABLES = 32
MAX_REPEATER_VARIABLE_NAME_BYTES = 64
MAX_REPEATER_VARIABLE_VALUE_BYTES = 4 * 1024
MAX_REPEATER_VARIABLE_BYTES = 32 * 1024
MAX_REPEATER_TEMPLATE_METHOD_BYTES = 256
MIN_REPEATER_TIMEOUT_MS = 100
MAX_REPEATER_TIMEOUT_MS = 30_000
MAX_OBJECT_EXPERIMENT_AUDIT_ENTRIES = 128
MAX_OBJECT_EXPERIMENT_MUTATIONS = 256
MAX_OBJECT_EXPERIMENT_PROPERTY_BYTES = 256
MAX_OBJECT_EXPERIMENT_VALUE_BYTES = 16 * 1024
MAX_OBJECT_EXPERIMENT_VALUE_DEPTH = 8
MAX_OBJECT_EXPERIMENT_VALUE_ENTRIES = 256
MAX_OBJECT_EXPERIMENT_STRING_BYTES = 4 * 1024
OBJECT_EXPERIMENT_NAVIGATION_TIMEOUT_SECONDS = 15.0
MAX_RUNTIME_HOOKS = 8
MAX_RUNTIME_HOOK_BREAKPOINTS = 64
MAX_RUNTIME_HOOK_RETURN_POINTS = 32
MAX_RUNTIME_HOOK_HITS = 512
MAX_RUNTIME_HOOK_RETAINED_HITS = 128
MAX_RUNTIME_HOOK_BINDINGS = 32
MAX_RUNTIME_HOOK_BINDING_PREVIEW_BYTES = 512
MAX_RUNTIME_HOOK_LABEL_BYTES = 128
MAX_RUNTIME_HOOK_CONDITION_BYTES = 1024
MAX_RUNTIME_HOOK_LOGIC_BYTES = 8 * 1024
MAX_RUNTIME_HOOK_RETURN_BYTES = 8 * 1024
RUNTIME_HOOK_EVALUATION_TIMEOUT_MS = 100
MAX_AUTOMATION_RECIPES = 16
MAX_AUTOMATION_AUTO_RECIPES = 8
MAX_AUTOMATION_RECIPE_SOURCE_BYTES = 16 * 1024
MAX_AUTOMATION_TOTAL_SOURCE_BYTES = 64 * 1024
MAX_AUTOMATION_LABEL_BYTES = 128
MAX_AUTOMATION_VARIABLES = 32
MAX_AUTOMATION_VARIABLE_NAME_BYTES = 128
MAX_AUTOMATION_VARIABLE_VALUE_BYTES = 4 * 1024
MAX_AUTOMATION_VARIABLE_BYTES = 16 * 1024
MAX_AUTOMATION_RUNS = 256
MAX_AUTOMATION_AUTO_RUNS = 64
MAX_AUTOMATION_RETAINED_RUNS = 64
MAX_AUTOMATION_LOGS = 32
MAX_AUTOMATION_LOG_BYTES = 1024
MAX_AUTOMATION_RESULT_BYTES = 16 * 1024
MAX_AUTOMATION_BINDING_REPORT_BYTES = 8 * 1024
AUTOMATION_EXECUTION_TIMEOUT_MS = 2_000
AUTOMATION_WATCHDOG_GRACE_SECONDS = 0.25
MAX_ACTION_SCOPE_TARGETS = 8
MAX_ACTION_SCOPE_PENDING_TRIGGERS = 16
REPEATER_VARIABLE_TOKEN = re.compile(r"\{\{(=)?([^{}]+)\}\}")
REPEATER_VARIABLE_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_.-]*\Z")
SENSITIVE_INTERCEPTION_HEADERS = {
    "authorization",
    "cookie",
    "proxy-authorization",
    "set-cookie",
}
FORBIDDEN_OBJECT_EXPERIMENT_PROPERTIES = {
    "__proto__",
    "constructor",
    "prototype",
}
MEMORY_ORIGIN_TRACE_FRAMEWORK_PATTERNS = (
    "/node_modules/",
    "react",
    "react-dom",
    "redux",
    "vue",
    "angular",
    "jquery",
    "lodash",
    "rxjs",
    "core-js",
    "regenerator-runtime",
    "polyfill",
    "webpack",
    "vite",
    "rollup",
    "parcel",
    "zone.js",
)
