# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojom") {
  sources = [ "common/native_probe_transport.mojom" ]

  public_deps = [ "//mojo/public/mojom/base" ]
}

source_set("queue") {
  sources = [
    "common/native_probe_queue.cc",
    "common/native_probe_queue.h",
  ]
}

component("renderer_sink") {
  output_name = "reverse_engineering_browser_renderer_sink"

  defines = [ "IS_REB_NATIVE_PROBE_SINK_IMPL" ]

  sources = [
    "common/native_probe_event.h",
    "renderer/native_probe_sink.cc",
    "renderer/native_probe_sink.h",
  ]

  deps = [ "//base" ]
}

source_set("renderer") {
  sources = [
    "common/native_vm_finding.h",
    "renderer/native_probe_transport.cc",
    "renderer/native_probe_transport.h",
  ]

  deps = [
    ":mojom",
    ":queue",
    ":renderer_sink",
    "//base",
    "//mojo/public/cpp/base",
    "//mojo/public/cpp/bindings",
  ]
}

source_set("browser") {
  sources = [
    "browser/native_artifact_body_tee.cc",
    "browser/native_artifact_body_tee.h",
    "browser/native_artifact_capture_sink.cc",
    "browser/native_artifact_capture_sink.h",
    "browser/native_artifact_socket_client.cc",
    "browser/native_artifact_socket_client.h",
    "browser/native_local_ipc_client.cc",
    "browser/native_local_ipc_client.h",
    "browser/native_network_capture_sink.cc",
    "browser/native_network_capture_sink.h",
    "browser/native_probe_host.cc",
    "browser/native_probe_host.h",
    "browser/native_probe_session.cc",
    "browser/native_probe_session.h",
    "browser/native_probe_socket_client.cc",
    "browser/native_probe_socket_client.h",
    "common/native_artifact_header.h",
    "common/native_probe_event.h",
    "common/native_probe_ipc.h",
    "common/native_vm_finding.h",
  ]

  deps = [
    ":mojom",
    ":queue",
    "//base",
    "//mojo/public/cpp/base",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//url",
  ]
}

executable("native_artifact_body_tee_unittests") {
  testonly = true
  sources = [
    "browser/native_artifact_body_tee.cc",
    "browser/native_artifact_body_tee_unittest.cc",
  ]

  deps = [
    "//base",
    "//base/test:test_support",
    "//mojo/core/embedder",
    "//mojo/public/cpp/system",
    "//testing/gtest",
  ]
}

executable("native_probe_sink_unittests") {
  testonly = true
  sources = [ "renderer/native_probe_sink_unittest.cc" ]

  deps = [
    ":renderer_sink",
    "//base",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}
