      if (new URLSearchParams(location.search).has('native')) document.documentElement.classList.add('native-shell');

      const sampleRequests = [
        { id: '78', path: '/api/profile', method: 'GET', status: 200, time: 64, type: 'xhr', origin: 'sample', start: 8, mid: 31, end: 43 },
        { id: '79', path: '/assets/cart.js', method: 'GET', status: 304, time: 18, type: 'js', origin: 'sample', start: 18, mid: 32, end: 40 },
        { id: '80', path: '/fingerprint/config', method: 'GET', status: 200, time: 91, type: 'xhr', origin: 'sample', start: 30, mid: 67, end: 79 },
        { id: '81', path: '/cart', method: 'POST', status: 201, time: 181, type: 'xhr', origin: 'sample', start: 43, mid: 73, end: 88, traceable: true }
      ];

      const sampleEvidence = [
        { relative: '0.000 ms', source: 'sample', category: 'network', type: 'request_field', correlation: 'req 81 · nav 100', value: 'body.device.fingerprint' },
        { relative: '-0.412 ms', source: 'sample', category: 'runtime', type: 'serialized_by', correlation: 'obj 17 · frame 200', value: 'JSON.stringify' },
        { relative: '-0.831 ms', source: 'sample', category: 'transform', type: 'encoded_by', correlation: 'artifact 300', value: 'Base64 · reversible match' },
        { relative: '-1.224 ms', source: 'sample', category: 'wasm', type: 'candidate_return', correlation: 'wasm 4 · frame 200', value: 'export generate · correlated only' },
        { relative: '-1.907 ms', source: 'sample', category: 'canvas', type: 'api_call', correlation: 'event 194 · frame 200', value: 'CanvasRenderingContext2D.getImageData' }
      ];

      const sampleArtifacts = [
        {
          protocol_version: 1, artifact_id: 'sample-300', session_id: '1', navigation_id: '100', frame_id: '200',
          parent_artifact_id: '0', creator_event_id: '79', kind: 'javascript', origin: 'sample',
          url: 'https://checkout.acme.test/assets/cart.js', mime_type: 'text/javascript', byte_size: 368,
          sha256: 'sample-preview-not-stored', sensitive: false,
          content: `export function buildPayload(cart, fingerprint) {
  const payload = {
    cart,
    device: {locale: navigator.language, fingerprint},
  };
  return JSON.stringify(payload);
}

export async function checkout(cart, fingerprint) {
  return fetch('/cart', {
    method: 'POST',
    headers: {'content-type': 'application/json'},
    body: buildPayload(cart, fingerprint),
  });
}`
        },
        {
          protocol_version: 1, artifact_id: 'sample-301', session_id: '1', navigation_id: '100', frame_id: '200',
          parent_artifact_id: 'sample-300', creator_event_id: '194', kind: 'wasm', origin: 'sample',
          url: 'https://checkout.acme.test/assets/fingerprint.wasm', mime_type: 'application/wasm', byte_size: 8,
          sha256: 'sample-preview-not-stored', sensitive: false,
          content: '00000000  00 61 73 6d 01 00 00 00                          |.asm....|'
        }
      ];

      const fieldSets = {
        body: [
          { key: 'cart', value: '{ 3 fields }', type: 'obj', depth: 0, group: true },
          { key: 'items', value: '[ { sku: "A14", qty: 1 } ]', type: 'arr', depth: 1 },
          { key: 'device', value: '{ 2 fields }', type: 'obj', depth: 1, group: true },
          { key: 'locale', value: '"en-US"', type: 'str', depth: 2 },
          { key: 'fingerprint', value: '"N2Y0YTFjZj…"', type: 'str', depth: 2, traceable: true, path: '$.device.fingerprint', label: 'Body' },
          { key: 'coupon', value: 'null', type: 'null', depth: 1 }
        ],
        headers: [
          { key: 'content-type', value: 'application/json', type: 'str', depth: 0 },
          { key: 'x-client-token', value: 'tkn_A7f3…', type: 'str', depth: 0, traceable: true, path: 'x-client-token', label: 'Header' },
          { key: 'accept-language', value: 'en-US', type: 'str', depth: 0 }
        ],
        cookies: [
          { key: 'session_proof', value: 'proof_42bf…', type: 'str', depth: 0, traceable: true, path: 'session_proof', label: 'Cookie' },
          { key: 'cart_id', value: 'cart_8e11', type: 'str', depth: 0 }
        ],
        raw: [
          { key: 'payload', value: '{"cart":{"items":[…],"device":{…}}}', type: 'bytes', depth: 0 }
        ]
      };

      const emptyApiCollection = () => ({
        contract_version: 1,
        document_kind: 'api-collection',
        generation: 0,
        updated_at_ms: 0,
        folders: [{id: 1, name: 'API Collection', parent_id: null, variables: []}],
        requests: [],
        limits: {
          folders: 32,
          requests: 128,
          folder_depth: 4,
          variables_per_scope: 32,
          variable_bytes_per_scope: 32 * 1024,
          request_body_bytes: 64 * 1024,
          document_bytes: 2 * 1024 * 1024
        }
      });

      const emptyLocalAnalystWorkspace = () => ({
        contract_version: 1,
        document_kind: 'local-analyst-workspace',
        generation: 0,
        updated_at_ms: 0,
        folders: [{id: 1, name: 'Analyst Workspace', parent_id: null}],
        files: [],
        limits: {
          folders: 32,
          files: 64,
          folder_depth: 4,
          file_bytes: 32 * 1024,
          total_file_bytes: 512 * 1024,
          document_bytes: 1024 * 1024,
          variables: 32,
          variable_value_bytes: 4 * 1024,
          variable_bytes: 16 * 1024,
          evidence_bytes: 768 * 1024,
          selected_artifact_bytes: 64 * 1024,
          execution_timeout_ms: 2000,
          logs: 64,
          log_bytes: 1024,
          result_bytes: 32 * 1024
        }
      });

      const emptyDecoderEngine = () => ({
        protocol_version: 1,
        available: false,
        busy: false,
        limits: {
          input_bytes: 1024 * 1024,
          output_bytes: 1024 * 1024,
          pipeline_steps: 16,
          retained_bytes: 4 * 1024 * 1024,
          jwt_bytes: 64 * 1024,
          secret_bytes: 4 * 1024,
          json_depth: 64,
          json_tokens: 100000,
          timeout_ms: 2000,
          operations: [],
          jwt_algorithms: ['HS256', 'HS384', 'HS512', 'none']
        }
      });

      const state = {
        events: [],
        requests: [...sampleRequests],
        artifacts: [...sampleArtifacts],
        openArtifactIds: ['sample-300'],
        selectedArtifactId: 'sample-300',
        artifactRefreshing: false,
        artifactEtag: null,
        sourceCollection: 'captured',
        openScriptIds: [],
        selectedScriptId: null,
        liveScriptContent: new Map(),
        pendingSourceLine: null,
        sourceCursor: null,
        sourcePretty: false,
        sourceTruncated: false,
        consoleOpen: false,
        debuggerSession: null,
        debuggerEtag: null,
        debuggerRefreshing: false,
        debuggerRefreshTimer: null,
        debuggerActionPending: false,
        debuggerError: null,
        debuggerRenderKeys: {},
        renderedConsoleSignature: null,
        selectedCallFrameId: null,
        editingBreakpointId: null,
        memoryMode: 'live',
        memoryResults: [],
        selectedMemoryResultId: null,
        memorySearchPending: false,
        memorySearchStatus: 'offline',
        memorySearchMessage: null,
        memorySearchMeta: null,
        memoryDiffBaseline: null,
        memoryTargetId: null,
        selectedRequestId: '81',
        inspectorTab: 'payload',
        fieldTab: 'body',
        selectedField: fieldSets.body.find(field => field.traceable),
        requestType: 'all',
        broker: 'connecting',
        refreshing: false,
        eventEtag: null,
        vmFindings: [],
        lastValidAnalysisFindings: [],
        eventVmFindings: [],
        malformedVmFindings: 0,
        selectedVmFindingId: null,
        vmAnalysisStatus: 'loading',
        vmAnalysisError: null,
        vmAnalysisRequestId: null,
        vmAnalysisEtag: null,
        originTrace: null,
        originTraceStatus: 'idle',
        originTraceError: null,
        originTraceKey: null,
        originTraceEtag: null,
        selectedTraceRow: null,
        originTraceGeneration: 0,
        experimentPending: false,
        experimentError: null,
        experimentPrefillKey: null,
        experimentMode: 'interceptor',
        actionScopeDraftMode: null,
        actionScopeDraftRevision: -1,
        objectSelectedResultId: null,
        objectSelectionSearchId: 0,
        automationEditingRecipeId: null,
        automationSelectedRunId: null,
        repeaterPrefillKey: null,
        repeaterSelectedHistoryId: null,
        repeaterExpectedHistoryId: null,
        repeaterVariablesKey: null,
        repeaterVariablesDirty: false,
        repeaterDraftDirty: false,
        repeaterCompareBaselineId: null,
        repeaterCompareCurrentId: null,
        repeaterComparisonKey: null,
        apiCollection: emptyApiCollection(),
        apiCollectionEtag: null,
        apiCollectionLoaded: false,
        apiCollectionRefreshing: false,
        apiCollectionSaving: false,
        apiCollectionStatus: 'loading',
        apiCollectionMessage: 'Loading the local API Collection…',
        collectionSelectedFolderId: 1,
        collectionSelectedRequestId: null,
        collectionExpandedFolderIds: new Set([1]),
        collectionRequestDraftId: null,
        collectionDraftDirty: false,
        collectionFolderDraftId: null,
        collectionFolderDirty: false,
        collectionSelectedHistoryId: null,
        collectionDeleteRequestId: null,
        collectionDeleteFolderId: null,
        localAnalyst: emptyLocalAnalystWorkspace(),
        localAnalystEtag: null,
        localAnalystLoaded: false,
        localAnalystRefreshing: false,
        localAnalystSaving: false,
        localAnalystStatus: 'loading',
        localAnalystMessage: 'Loading the local analyst workspace…',
        localAnalystRunner: null,
        analystSelectedFolderId: 1,
        analystSelectedFileId: null,
        analystExpandedFolderIds: new Set([1]),
        analystDraftDirty: false,
        analystFolderDraftId: null,
        analystFolderDirty: false,
        analystDeleteFileId: null,
        analystDeleteFolderId: null,
        analystRunPending: false,
        analystActiveRunId: null,
        analystNextRunId: 1,
        analystTotalRuns: 0,
        analystHistoryEvictions: 0,
        analystRuns: [],
        analystSelectedRunId: null,
        decoderEngine: emptyDecoderEngine(),
        decoderStatus: 'loading',
        decoderMessage: 'Checking the native decoder engine…',
        decoderRefreshing: false,
        toolsTab: 'decoder',
        decoderInputSnapshot: null,
        decoderSteps: [],
        decoderSelectedStepId: null,
        decoderNextOperationId: 1,
        decoderPending: false,
        decoderView: 'text',
        jwtResult: null,
        jwtPending: false,
        signalProfile: null,
        signalProfileStatus: 'idle',
        signalProfileError: null,
        signalProfileKey: null,
        signalProfileEtag: null,
        signalProfileGeneration: 0
      };

      const elements = {
        capture: document.querySelector('#capture-state'),
        broker: document.querySelector('#broker-status'),
        updated: document.querySelector('#updated-status'),
        gaps: document.querySelector('#gap-status'),
        requestCount: document.querySelector('#request-count'),
        requestFilter: document.querySelector('#request-filter'),
        requestRows: document.querySelector('#request-rows'),
        networkNotice: document.querySelector('#network-notice'),
        selectedMethod: document.querySelector('#selected-method'),
        selectedStatus: document.querySelector('#selected-status'),
        selectedUrl: document.querySelector('#selected-url'),
        requestInspector: document.querySelector('#request-inspector'),
        prompt: document.querySelector('#request-prompt'),
        fieldTabs: document.querySelector('#field-tabs'),
        fieldTree: document.querySelector('#field-tree'),
        traceDock: document.querySelector('#trace-dock'),
        traceTarget: document.querySelector('#trace-target'),
        traceButton: document.querySelector('#trace-origin'),
        requestMemoryPivot: document.querySelector('#request-memory-pivot'),
        requestVmCandidates: document.querySelector('#request-vm-candidates'),
        backtraceSubtitle: document.querySelector('#backtrace-subtitle'),
        backtraceSteps: document.querySelector('#backtrace-steps'),
        traceRequest: document.querySelector('#trace-request'),
        traceLoad: document.querySelector('#trace-load'),
        traceEvidence: document.querySelector('#trace-evidence'),
        traceNotice: document.querySelector('#trace-notice'),
        traceEmpty: document.querySelector('#trace-empty'),
        traceEmptyTitle: document.querySelector('#trace-empty-title'),
        traceEmptyMessage: document.querySelector('#trace-empty-message'),
        traceFirstRequest: document.querySelector('#trace-first-request'),
        traceContent: document.querySelector('#trace-content'),
        traceStepDetails: document.querySelector('#trace-step-details'),
        evidenceRows: document.querySelector('#evidence-rows'),
        evidenceCount: document.querySelector('#evidence-count'),
        evidenceLinkCount: document.querySelector('#evidence-link-count'),
        coverageValue: document.querySelector('#coverage-value'),
        requestRepeaterPivot: document.querySelector('#request-repeater-pivot'),
        requestDecoderPivot: document.querySelector('#request-decoder-pivot'),
        requestCollectionPivot: document.querySelector('#request-collection-pivot'),
        experimentTitle: document.querySelector('#experiment-title'),
        experimentModeButtons: [...document.querySelectorAll('[data-experiment-mode]')],
        interceptionWorkspace: document.querySelector('#interception-workspace'),
        repeaterWorkspace: document.querySelector('#repeater-workspace'),
        objectWorkspace: document.querySelector('#object-workspace'),
        hooksWorkspace: document.querySelector('#hooks-workspace'),
        automationWorkspace: document.querySelector('#automation-workspace'),
        experimentSubtitle: document.querySelector('#experiment-subtitle'),
        experimentNotice: document.querySelector('#experiment-notice'),
        actionScopePanel: document.querySelector('#action-scope-panel'),
        actionScopeBadge: document.querySelector('#action-scope-badge'),
        actionScopeMessage: document.querySelector('#action-scope-message'),
        actionScopeGlobal: document.querySelector('#action-scope-global'),
        actionScopeTargeted: document.querySelector('#action-scope-targeted'),
        actionScopeTarget: document.querySelector('#action-scope-target'),
        actionScopeApply: document.querySelector('#action-scope-apply'),
        actionScopeAddForm: document.querySelector('#action-scope-add-form'),
        actionScopeNewUrl: document.querySelector('#action-scope-new-url'),
        actionScopeAdd: document.querySelector('#action-scope-add'),
        actionScopeTargets: document.querySelector('#action-scope-targets'),
        experimentContextMessage: document.querySelector('#experiment-context-message'),
        experimentContextBadge: document.querySelector('#experiment-context-badge'),
        experimentStorageState: document.querySelector('#experiment-storage-state'),
        experimentPendingCount: document.querySelector('#experiment-pending-count'),
        experimentCreate: document.querySelector('#experiment-create'),
        experimentDispose: document.querySelector('#experiment-dispose'),
        experimentClear: document.querySelector('#experiment-clear'),
        experimentRuleForm: document.querySelector('#experiment-rule-form'),
        experimentUrlPattern: document.querySelector('#experiment-url-pattern'),
        experimentRuleMode: document.querySelector('#experiment-rule-mode'),
        experimentMethodFilter: document.querySelector('#experiment-method-filter'),
        experimentRewriteOptions: document.querySelector('#experiment-rewrite-options'),
        experimentRewriteUrl: document.querySelector('#experiment-rewrite-url'),
        experimentRewriteMethod: document.querySelector('#experiment-rewrite-method'),
        experimentRewriteHeaders: document.querySelector('#experiment-rewrite-headers'),
        experimentRewriteBody: document.querySelector('#experiment-rewrite-body'),
        experimentFulfillOptions: document.querySelector('#experiment-fulfill-options'),
        experimentResponseCode: document.querySelector('#experiment-response-code'),
        experimentResponseHeaders: document.querySelector('#experiment-response-headers'),
        experimentResponseBody: document.querySelector('#experiment-response-body'),
        experimentArmRule: document.querySelector('#experiment-arm-rule'),
        experimentRuleBadge: document.querySelector('#experiment-rule-badge'),
        experimentRequestForm: document.querySelector('#experiment-request-form'),
        experimentRequestUrl: document.querySelector('#experiment-request-url'),
        experimentRequestMethod: document.querySelector('#experiment-request-method'),
        experimentRequestHeaders: document.querySelector('#experiment-request-headers'),
        experimentRequestBody: document.querySelector('#experiment-request-body'),
        experimentRun: document.querySelector('#experiment-run'),
        experimentResultMeta: document.querySelector('#experiment-result-meta'),
        experimentResultBadge: document.querySelector('#experiment-result-badge'),
        experimentResult: document.querySelector('#experiment-result'),
        experimentAuditCount: document.querySelector('#experiment-audit-count'),
        experimentAudit: document.querySelector('#experiment-audit'),
        objectContextMessage: document.querySelector('#object-context-message'),
        objectContextBadge: document.querySelector('#object-context-badge'),
        objectStorageState: document.querySelector('#object-storage-state'),
        objectPageState: document.querySelector('#object-page-state'),
        objectCreate: document.querySelector('#object-create'),
        objectDispose: document.querySelector('#object-dispose'),
        objectNavigationForm: document.querySelector('#object-navigation-form'),
        objectPageUrl: document.querySelector('#object-page-url'),
        objectNavigate: document.querySelector('#object-navigate'),
        objectPageBadge: document.querySelector('#object-page-badge'),
        objectSearchForm: document.querySelector('#object-search-form'),
        objectPropertyQuery: document.querySelector('#object-property-query'),
        objectValueQuery: document.querySelector('#object-value-query'),
        objectClassQuery: document.querySelector('#object-class-query'),
        objectShapeQuery: document.querySelector('#object-shape-query'),
        objectSimilarityThreshold: document.querySelector('#object-similarity-threshold'),
        objectRegex: document.querySelector('#object-regex'),
        objectCaseSensitive: document.querySelector('#object-case-sensitive'),
        objectShapeValues: document.querySelector('#object-shape-values'),
        objectSearch: document.querySelector('#object-search'),
        objectSearchBadge: document.querySelector('#object-search-badge'),
        objectSearchMeta: document.querySelector('#object-search-meta'),
        objectResultCount: document.querySelector('#object-result-count'),
        objectResults: document.querySelector('#object-results'),
        objectSelectionMeta: document.querySelector('#object-selection-meta'),
        objectMutationBadge: document.querySelector('#object-mutation-badge'),
        objectPreview: document.querySelector('#object-preview'),
        objectMutationForm: document.querySelector('#object-mutation-form'),
        objectOperation: document.querySelector('#object-operation'),
        objectMutationProperty: document.querySelector('#object-mutation-property'),
        objectValueField: document.querySelector('#object-value-field'),
        objectMutationValue: document.querySelector('#object-mutation-value'),
        objectConfirm: document.querySelector('#object-confirm'),
        objectMutate: document.querySelector('#object-mutate'),
        objectMutationResult: document.querySelector('#object-mutation-result'),
        objectAuditCount: document.querySelector('#object-audit-count'),
        objectAudit: document.querySelector('#object-audit'),
        hooksContextMessage: document.querySelector('#hooks-context-message'),
        hooksContextBadge: document.querySelector('#hooks-context-badge'),
        hooksStorageState: document.querySelector('#hooks-storage-state'),
        hooksPointUsage: document.querySelector('#hooks-point-usage'),
        hooksCreate: document.querySelector('#hooks-create'),
        hooksDispose: document.querySelector('#hooks-dispose'),
        hooksClear: document.querySelector('#hooks-clear'),
        hooksNavigationForm: document.querySelector('#hooks-navigation-form'),
        hooksPageUrl: document.querySelector('#hooks-page-url'),
        hooksNavigate: document.querySelector('#hooks-navigate'),
        hooksPageBadge: document.querySelector('#hooks-page-badge'),
        hooksStateBadge: document.querySelector('#hooks-state-badge'),
        hooksConfirm: document.querySelector('#hooks-confirm'),
        hooksArm: document.querySelector('#hooks-arm'),
        hooksDisarm: document.querySelector('#hooks-disarm'),
        hooksDefinitionCount: document.querySelector('#hooks-definition-count'),
        hooksDefinitionForm: document.querySelector('#hooks-definition-form'),
        hooksLabel: document.querySelector('#hooks-label'),
        hooksScript: document.querySelector('#hooks-script'),
        hooksLine: document.querySelector('#hooks-line'),
        hooksColumn: document.querySelector('#hooks-column'),
        hooksEntryEnabled: document.querySelector('#hooks-entry-enabled'),
        hooksReturnEnabled: document.querySelector('#hooks-return-enabled'),
        hooksCondition: document.querySelector('#hooks-condition'),
        hooksEntryLogic: document.querySelector('#hooks-entry-logic'),
        hooksReturnLogic: document.querySelector('#hooks-return-logic'),
        hooksReturnMode: document.querySelector('#hooks-return-mode'),
        hooksReturnValueField: document.querySelector('#hooks-return-value-field'),
        hooksReturnValue: document.querySelector('#hooks-return-value'),
        hooksAdd: document.querySelector('#hooks-add'),
        hooksDefinitionBadge: document.querySelector('#hooks-definition-badge'),
        hooksDefinitions: document.querySelector('#hooks-definitions'),
        hooksHitMeta: document.querySelector('#hooks-hit-meta'),
        hooksHitCount: document.querySelector('#hooks-hit-count'),
        hooksHits: document.querySelector('#hooks-hits'),
        automationContextMessage: document.querySelector('#automation-context-message'),
        automationContextBadge: document.querySelector('#automation-context-badge'),
        automationStorageState: document.querySelector('#automation-storage-state'),
        automationRunUsage: document.querySelector('#automation-run-usage'),
        automationCreate: document.querySelector('#automation-create'),
        automationDispose: document.querySelector('#automation-dispose'),
        automationClear: document.querySelector('#automation-clear'),
        automationNavigationForm: document.querySelector('#automation-navigation-form'),
        automationPageUrl: document.querySelector('#automation-page-url'),
        automationNavigate: document.querySelector('#automation-navigate'),
        automationPageBadge: document.querySelector('#automation-page-badge'),
        automationStateBadge: document.querySelector('#automation-state-badge'),
        automationVariables: document.querySelector('#automation-variables'),
        automationConfirm: document.querySelector('#automation-confirm'),
        automationArm: document.querySelector('#automation-arm'),
        automationDisarm: document.querySelector('#automation-disarm'),
        automationCancel: document.querySelector('#automation-cancel'),
        automationRecipeCount: document.querySelector('#automation-recipe-count'),
        automationRecipeForm: document.querySelector('#automation-recipe-form'),
        automationLabel: document.querySelector('#automation-label'),
        automationTrigger: document.querySelector('#automation-trigger'),
        automationEnabled: document.querySelector('#automation-enabled'),
        automationSource: document.querySelector('#automation-source'),
        automationSave: document.querySelector('#automation-save'),
        automationCancelEdit: document.querySelector('#automation-cancel-edit'),
        automationSourceUsage: document.querySelector('#automation-source-usage'),
        automationRecipes: document.querySelector('#automation-recipes'),
        automationRunMeta: document.querySelector('#automation-run-meta'),
        automationRunCount: document.querySelector('#automation-run-count'),
        automationRuns: document.querySelector('#automation-runs'),
        automationResultMeta: document.querySelector('#automation-result-meta'),
        automationResultBadge: document.querySelector('#automation-result-badge'),
        automationResult: document.querySelector('#automation-result'),
        repeaterContextMessage: document.querySelector('#repeater-context-message'),
        repeaterContextBadge: document.querySelector('#repeater-context-badge'),
        repeaterStorageState: document.querySelector('#repeater-storage-state'),
        repeaterHistoryUsage: document.querySelector('#repeater-history-usage'),
        repeaterCreate: document.querySelector('#repeater-create'),
        repeaterDispose: document.querySelector('#repeater-dispose'),
        repeaterClearHistory: document.querySelector('#repeater-clear-history'),
        repeaterHistoryBadge: document.querySelector('#repeater-history-badge'),
        repeaterHistoryBytes: document.querySelector('#repeater-history-bytes'),
        repeaterHistoryPrev: document.querySelector('#repeater-history-prev'),
        repeaterHistoryNext: document.querySelector('#repeater-history-next'),
        repeaterHistory: document.querySelector('#repeater-history'),
        repeaterVariableBadge: document.querySelector('#repeater-variable-badge'),
        repeaterVariableForm: document.querySelector('#repeater-variable-form'),
        repeaterVariables: document.querySelector('#repeater-variables'),
        repeaterApplyVariables: document.querySelector('#repeater-apply-variables'),
        repeaterRequestBadge: document.querySelector('#repeater-request-badge'),
        repeaterRequestForm: document.querySelector('#repeater-request-form'),
        repeaterRequestUrl: document.querySelector('#repeater-request-url'),
        repeaterRequestMethod: document.querySelector('#repeater-request-method'),
        repeaterRequestTimeout: document.querySelector('#repeater-request-timeout'),
        repeaterRequestHeaders: document.querySelector('#repeater-request-headers'),
        repeaterRequestBody: document.querySelector('#repeater-request-body'),
        repeaterVariableStatus: document.querySelector('#repeater-variable-status'),
        repeaterSend: document.querySelector('#repeater-send'),
        repeaterCancel: document.querySelector('#repeater-cancel'),
        repeaterCopyResolved: document.querySelector('#repeater-copy-resolved'),
        repeaterActiveRequest: document.querySelector('#repeater-active-request'),
        repeaterResponseMeta: document.querySelector('#repeater-response-meta'),
        repeaterResponseBadge: document.querySelector('#repeater-response-badge'),
        repeaterResponse: document.querySelector('#repeater-response'),
        repeaterCompareBaseline: document.querySelector('#repeater-compare-baseline'),
        repeaterCompareCurrent: document.querySelector('#repeater-compare-current'),
        repeaterCompare: document.querySelector('#repeater-compare'),
        repeaterComparisonBadge: document.querySelector('#repeater-comparison-badge'),
        repeaterComparison: document.querySelector('#repeater-comparison'),
        collectionGeneration: document.querySelector('#collection-generation'),
        collectionNotice: document.querySelector('#collection-notice'),
        collectionCount: document.querySelector('#collection-count'),
        collectionNewFolder: document.querySelector('#collection-new-folder'),
        collectionNewRequest: document.querySelector('#collection-new-request'),
        collectionNewFolderForm: document.querySelector('#collection-new-folder-form'),
        collectionNewFolderName: document.querySelector('#collection-new-folder-name'),
        collectionConfirmFolder: document.querySelector('#collection-confirm-folder'),
        collectionCancelFolder: document.querySelector('#collection-cancel-folder'),
        collectionTree: document.querySelector('#collection-tree'),
        collectionFolderForm: document.querySelector('#collection-folder-form'),
        collectionFolderName: document.querySelector('#collection-folder-name'),
        collectionFolderParent: document.querySelector('#collection-folder-parent'),
        collectionFolderVariables: document.querySelector('#collection-folder-variables'),
        collectionSaveFolder: document.querySelector('#collection-save-folder'),
        collectionDeleteFolder: document.querySelector('#collection-delete-folder'),
        collectionEditorEmpty: document.querySelector('#collection-editor-empty'),
        collectionRequestBadge: document.querySelector('#collection-request-badge'),
        collectionRequestForm: document.querySelector('#collection-request-form'),
        collectionRequestName: document.querySelector('#collection-request-name'),
        collectionRequestFolder: document.querySelector('#collection-request-folder'),
        collectionRequestUrl: document.querySelector('#collection-request-url'),
        collectionRequestMethod: document.querySelector('#collection-request-method'),
        collectionRequestTimeout: document.querySelector('#collection-request-timeout'),
        collectionRequestHeaders: document.querySelector('#collection-request-headers'),
        collectionRequestBody: document.querySelector('#collection-request-body'),
        collectionRequestVariables: document.querySelector('#collection-request-variables'),
        collectionVariableStatus: document.querySelector('#collection-variable-status'),
        collectionSaveRequest: document.querySelector('#collection-save-request'),
        collectionDuplicateRequest: document.querySelector('#collection-duplicate-request'),
        collectionDeleteRequest: document.querySelector('#collection-delete-request'),
        collectionContextMessage: document.querySelector('#collection-context-message'),
        collectionContextBadge: document.querySelector('#collection-context-badge'),
        collectionCreateContext: document.querySelector('#collection-create-context'),
        collectionRun: document.querySelector('#collection-run'),
        collectionCancel: document.querySelector('#collection-cancel'),
        collectionHistoryBadge: document.querySelector('#collection-history-badge'),
        collectionHistory: document.querySelector('#collection-history'),
        collectionResponseMeta: document.querySelector('#collection-response-meta'),
        collectionResponseBadge: document.querySelector('#collection-response-badge'),
        collectionResponse: document.querySelector('#collection-response'),
        sourceTree: document.querySelector('#source-tree'),
        sourceEditorTabs: document.querySelector('#source-editor-tabs'),
        sourceLocation: document.querySelector('#source-location'),
        sourceSearch: document.querySelector('#source-search'),
        sourcePretty: document.querySelector('#source-pretty'),
        sourceHookPivot: document.querySelector('#source-hook-pivot'),
        sourceCodeWrap: document.querySelector('#source-code-wrap'),
        sourceCode: document.querySelector('#source-code'),
        sourceCodeEmpty: document.querySelector('#source-code-empty'),
        sourcePosition: document.querySelector('#source-position'),
        sourceSize: document.querySelector('#source-size'),
        sourceViewKind: document.querySelector('#source-view-kind'),
        sourceLanguage: document.querySelector('#source-language'),
        sourceHash: document.querySelector('#source-hash'),
        artifactFacts: document.querySelector('#artifact-facts'),
        sourcesEditor: document.querySelector('.sources-editor'),
        consoleToggle: document.querySelector('#console-toggle'),
        consoleDrawer: document.querySelector('#console-drawer'),
        consoleEntries: document.querySelector('#console-entries'),
        consoleCount: document.querySelector('#console-count'),
        consoleClear: document.querySelector('#console-clear'),
        debugState: document.querySelector('#debug-state'),
        debugResume: document.querySelector('#debug-resume'),
        debugPause: document.querySelector('#debug-pause'),
        debugStepOver: document.querySelector('#debug-step-over'),
        debugStepInto: document.querySelector('#debug-step-into'),
        debugStepOut: document.querySelector('#debug-step-out'),
        debugBreakpointsActive: document.querySelector('#debug-breakpoints-active'),
        watchForm: document.querySelector('#watch-form'),
        watchExpression: document.querySelector('#watch-expression'),
        watchList: document.querySelector('#watch-list'),
        breakpointList: document.querySelector('#breakpoint-list'),
        scopeList: document.querySelector('#scope-list'),
        callStack: document.querySelector('#call-stack'),
        pauseOnExceptions: document.querySelector('#pause-on-exceptions'),
        xhrBreakpointForm: document.querySelector('#xhr-breakpoint-form'),
        xhrBreakpointPattern: document.querySelector('#xhr-breakpoint-pattern'),
        xhrBreakpointList: document.querySelector('#xhr-breakpoint-list'),
        eventBreakpointList: document.querySelector('#event-breakpoint-list'),
        memoryNotice: document.querySelector('#memory-notice'),
        memorySearchForm: document.querySelector('#memory-search-form'),
        memoryModeButtons: [...document.querySelectorAll('[data-memory-mode]')],
        memoryPropertyQuery: document.querySelector('#memory-property-query'),
        memoryValueQuery: document.querySelector('#memory-value-query'),
        memoryValueCaption: document.querySelector('#memory-value-caption'),
        memoryReferenceScope: document.querySelector('#memory-reference-scope'),
        memoryOriginBefore: document.querySelector('#memory-origin-before'),
        memoryOriginAfter: document.querySelector('#memory-origin-after'),
        memoryOriginStop: document.querySelector('#memory-origin-stop'),
        memoryOriginReset: document.querySelector('#memory-origin-reset'),
        memoryClassQuery: document.querySelector('#memory-class-query'),
        memoryShapeQuery: document.querySelector('#memory-shape-query'),
        memorySimilarityThreshold: document.querySelector('#memory-similarity-threshold'),
        memoryRegex: document.querySelector('#memory-regex'),
        memoryCaseSensitive: document.querySelector('#memory-case-sensitive'),
        memoryShapeValues: document.querySelector('#memory-shape-values'),
        memorySearchButton: document.querySelector('#memory-search-button'),
        memorySearchHelp: document.querySelector('#memory-search-help'),
        memoryDiffControls: document.querySelector('#memory-diff-controls'),
        memoryBaselineTitle: document.querySelector('#memory-baseline-title'),
        memoryBaselineMeta: document.querySelector('#memory-baseline-meta'),
        memoryCaptureBaseline: document.querySelector('#memory-capture-baseline'),
        memoryClearBaseline: document.querySelector('#memory-clear-baseline'),
        memoryCompareSnapshot: document.querySelector('#memory-compare-snapshot'),
        memoryResultLabel: document.querySelector('#memory-result-label'),
        memoryResultCount: document.querySelector('#memory-result-count'),
        memoryResults: document.querySelector('#memory-results'),
        memoryDetail: document.querySelector('#memory-detail'),
        quickOpen: document.querySelector('#quick-open'),
        quickOpenInput: document.querySelector('#quick-open-input'),
        quickOpenResults: document.querySelector('#quick-open-results'),
        vmNotice: document.querySelector('#vm-notice'),
        vmCount: document.querySelector('#vm-count'),
        vmList: document.querySelector('#vm-list'),
        vmDetail: document.querySelector('#vm-detail')
      };

      const analystElements = {
        generation: document.querySelector('#analyst-generation'),
        runnerBadge: document.querySelector('#analyst-runner-badge'),
        notice: document.querySelector('#analyst-notice'),
        fileCount: document.querySelector('#analyst-file-count'),
        folderUsage: document.querySelector('#analyst-folder-usage'),
        contentUsage: document.querySelector('#analyst-content-usage'),
        newFolder: document.querySelector('#analyst-new-folder'),
        newScript: document.querySelector('#analyst-new-script'),
        newNote: document.querySelector('#analyst-new-note'),
        tree: document.querySelector('#analyst-tree'),
        folderForm: document.querySelector('#analyst-folder-form'),
        folderName: document.querySelector('#analyst-folder-name'),
        folderParent: document.querySelector('#analyst-folder-parent'),
        saveFolder: document.querySelector('#analyst-save-folder'),
        deleteFolder: document.querySelector('#analyst-delete-folder'),
        editorBadge: document.querySelector('#analyst-editor-badge'),
        editorEmpty: document.querySelector('#analyst-editor-empty'),
        editorForm: document.querySelector('#analyst-editor-form'),
        name: document.querySelector('#analyst-name'),
        folder: document.querySelector('#analyst-folder'),
        kind: document.querySelector('#analyst-kind'),
        language: document.querySelector('#analyst-language'),
        content: document.querySelector('#analyst-content'),
        draftStatus: document.querySelector('#analyst-draft-status'),
        save: document.querySelector('#analyst-save'),
        revert: document.querySelector('#analyst-revert'),
        deleteFile: document.querySelector('#analyst-delete'),
        runForm: document.querySelector('#analyst-run-form'),
        variables: document.querySelector('#analyst-variables'),
        includeEvents: document.querySelector('#analyst-include-events'),
        includeArtifacts: document.querySelector('#analyst-include-artifacts'),
        includeTrace: document.querySelector('#analyst-include-trace'),
        includeSignals: document.querySelector('#analyst-include-signals'),
        includeVm: document.querySelector('#analyst-include-vm'),
        includeSelected: document.querySelector('#analyst-include-selected'),
        sensitiveRow: document.querySelector('#analyst-sensitive-row'),
        confirmSensitive: document.querySelector('#analyst-confirm-sensitive'),
        confirm: document.querySelector('#analyst-confirm'),
        run: document.querySelector('#analyst-run'),
        cancel: document.querySelector('#analyst-cancel'),
        clearHistory: document.querySelector('#analyst-clear-history'),
        snapshotBadge: document.querySelector('#analyst-snapshot-badge'),
        historyBadge: document.querySelector('#analyst-history-badge'),
        history: document.querySelector('#analyst-history'),
        resultMeta: document.querySelector('#analyst-result-meta'),
        resultBadge: document.querySelector('#analyst-result-badge'),
        result: document.querySelector('#analyst-result')
      };

      const toolsElements = {
        engineBadge: document.querySelector('#decoder-engine-badge'),
        notice: document.querySelector('#tools-notice'),
        tabs: [...document.querySelectorAll('[data-tools-tab]')],
        decoderPanel: document.querySelector('#tools-panel-decoder'),
        jwtPanel: document.querySelector('#tools-panel-jwt'),
        form: document.querySelector('#decoder-form'),
        inputEncoding: document.querySelector('#decoder-input-encoding'),
        operation: document.querySelector('#decoder-operation'),
        input: document.querySelector('#decoder-input'),
        inputBadge: document.querySelector('#decoder-input-badge'),
        append: document.querySelector('#decoder-append'),
        useField: document.querySelector('#decoder-use-field'),
        removeAfter: document.querySelector('#decoder-remove-after'),
        reset: document.querySelector('#decoder-reset'),
        pipelineBadge: document.querySelector('#decoder-pipeline-badge'),
        pipeline: document.querySelector('#decoder-pipeline'),
        outputMeta: document.querySelector('#decoder-output-meta'),
        outputBadge: document.querySelector('#decoder-output-badge'),
        viewButtons: [...document.querySelectorAll('[data-decoder-view]')],
        output: document.querySelector('#decoder-output'),
        copyOutput: document.querySelector('#decoder-copy-output'),
        selectedBytes: document.querySelector('#decoder-selected-bytes'),
        retainedBytes: document.querySelector('#decoder-retained-bytes'),
        duration: document.querySelector('#decoder-duration'),
        jwtInspectForm: document.querySelector('#jwt-inspect-form'),
        jwtToken: document.querySelector('#jwt-token'),
        jwtSecret: document.querySelector('#jwt-secret'),
        jwtInspect: document.querySelector('#jwt-inspect'),
        jwtVerify: document.querySelector('#jwt-verify'),
        jwtClear: document.querySelector('#jwt-clear'),
        jwtCreateForm: document.querySelector('#jwt-create-form'),
        jwtPayload: document.querySelector('#jwt-payload'),
        jwtAlgorithm: document.querySelector('#jwt-algorithm'),
        jwtExpiry: document.querySelector('#jwt-expiry'),
        jwtCreateSecret: document.querySelector('#jwt-create-secret'),
        jwtUnsignedRow: document.querySelector('#jwt-unsigned-row'),
        jwtConfirmUnsigned: document.querySelector('#jwt-confirm-unsigned'),
        jwtCreate: document.querySelector('#jwt-create'),
        jwtResultMessage: document.querySelector('#jwt-result-message'),
        jwtResultBadge: document.querySelector('#jwt-result-badge'),
        jwtStatus: document.querySelector('#jwt-status'),
        jwtClaims: document.querySelector('#jwt-claims'),
        jwtHeader: document.querySelector('#jwt-header'),
        jwtPayloadOutput: document.querySelector('#jwt-payload-output')
      };
